### ISSUE TITLE
Recommended git project for jasonette ios has build errors

### ISSUE THREAD

**Issue by jstorq** [jasonelle-archive/jasonelle-v2#109]
I evidently grabbed an original zip file for JSONETTE-ios master code line that was out of date as I ran into issues submitting to the App Connect as specified here: https://github.com/jasonelle/jasonelle/issues/108

I then cloned the recommended project, git@github.com:jasonelle/jasonette-ios.git, but there are build errors.  I tried both on the develop branch (what was recommended) and also the master branch.  Neither successfully build.  See screenshot for errors.

![Screen Shot 2021-02-26 at 4 35 36 PM](https://user-images.githubusercontent.com/7968831/109366459-b7b8f200-7850-11eb-87b4-c6d6a4fc7121.png)

Any ideas?  Thanks.

**Comment by clsource** [comment]
Yes this is probably due to Pods missing.

Execute `pod install` on the project using cocoapods.
Should solve the issue :)

**Comment by jstorq** [comment]
Thanks.  I've done that now:

![Screen Shot 2021-03-01 at 7 20 48 AM](https://user-images.githubusercontent.com/7968831/109510342-1d7ac900-7a5f-11eb-94b7-3e7af048bb57.png)

But am still getting a build error:

![Screen Shot 2021-03-01 at 7 22 55 AM](https://user-images.githubusercontent.com/7968831/109510263-08059f00-7a5f-11eb-9575-6fd2def130ae.png)

Any other ideas?

Thanks.  Jason

**Comment by clsource** [comment]
mmm maybe that dependency needs some checks.
let me see what can be done

**Comment by clsource** [comment]
It seems is available.


I downloaded a new copy of the project and run in a clean build. Although it has warnings it builds successfully.

![imagen](https://user-images.githubusercontent.com/292738/109536840-f80cb000-7a9c-11eb-98da-6d17208b6a2b.png)

Please try deleting the Pods directory and executing `pod install` again.

**Comment by clsource** [comment]
Ok I updated the Xcode Project to ios 12. Still has some warnings but at least now Xcode does not complains about recommended settings.

**Comment by jstorq** [comment]
Thank you!  I appreciate your quick response.  I will give it a go.

**Comment by jstorq** [comment]
FYI, I have now submitted a build successfully to the App Store Connect for review, hopefully will get approved for testing in Testflight shortly.  Thank you for the framework.  Really a huge help to deliver a consistent solution across multiple platforms quickly.  Thank you!
